use escola_att

CREATE TABLE IF NOT EXISTS alunos (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(45) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    data_cad TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    matricula VARCHAR(7) UNIQUE NOT NULL,
    l / curso VARCHAR(50) NOT NULL,
    mediaFinal DECIMAL(10, 2)
);

CREATE TABLE IF NOT EXISTS professores (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(45) NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    data_cad TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    disciplina VARCHAR(50) NOT NULL,
    cargaHoraria INT NOT NULL
);